---
title: "Analyze performance on synthetic data"
author: "Daan Hazelaar"
date: '2022-07-08'
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(VariantAnnotation)
```


```{r}
load(file = "../results/resultsSyntheticAllTools.RData")
load(file = "../data/parameters_synthetic_data.RData")
load(file = "../data/synthetic_data.RData")
load(file = "../results/resultsSyntheticKatdetectrAMOC.RData")
load(file = "../results/resultsSyntheticKatdetectrBinSeg.RData")
source(file = "./function_calculateMetrics.R")
source(file = "./function_calculateConfusionVariants.R")


theme_Job <- ggplot2::theme(
    legend.position = 'bottom',
    legend.direction = 'horizontal',
    text = ggplot2::element_text(size=9, family='Helvetica', face = 'bold'),
    axis.text.x = ggtext::element_markdown(),
    axis.title.x = ggtext::element_textbox_simple(width = NULL, halign = .5),
    axis.title.y = ggtext::element_textbox_simple(size = 8, orientation = 'left-rotated', width = NULL, halign = .5),
    strip.text = ggtext::element_textbox_simple(width = NULL, halign = .5),
    panel.grid.major.x = ggplot2::element_line(colour = 'grey90', linetype = 'dotted'),
    panel.grid.major.y = ggplot2::element_line(colour = '#E5E5E5', linetype = 'dotted'),
    panel.grid.minor.y = ggplot2::element_blank(),
    panel.background = ggplot2::element_rect(fill = NA, colour = 'black'),
    panel.border = ggplot2::element_rect(fill = NA, colour = NA),
    strip.background = ggplot2::element_rect(colour = 'black', fill = 'white'),
    legend.text = ggtext::element_markdown()
)
```

Descriptive statistics of the synthetic data.
```{r}
descriptive_synthetic_data <- dataSynthetic$reportedKataegisFoci |> 
    filter(kataegis) |> 
    left_join(parameters, by = c("sampleNames" = "parmNames")) |> 
    group_by(sampleNames) |> 
    mutate(
        totalVariantsSample = sum(totalVariants)
    ) |> 
    ungroup() |> 
    dplyr::select(!c(start, end, totalVariants)) |> 
    distinct() |> 
    group_by(nBackgroundMuts) |> 
    summarise(
        totalVariantsTMB = sum(totalVariantsSample),
        nKataegisFociTMB = sum(nKataegisFoci)
    )
```


Combine results into a dataframe and add columns needed for further analysis.
```{r}
resultsSynthetic <- dplyr::bind_rows("kataegis" = resultsSyntheticAllTools$kataegis, 
                                     "MafTools" = resultsSyntheticAllTools$maftools, 
                                     "SeqKat" = resultsSyntheticAllTools$seqkat,
                                     "ClusteredMutations" = resultsSyntheticAllTools$clusteredMutations,
                                     "katdetectr" = resultsSyntheticAllTools$katdetectr,
                                     "katdetectrAMOC" = resultsSyntheticKatdetectrAMOC,
                                     "katdetectrBinSeg" = resultsSyntheticKatdetectrBinSeg,
                                     "SigProfilerClusters" = resultsSyntheticAllTools$sigProfilerClusters,
                                     .id = "package") |> 
    # join the parameters setting used for generating the synthethic data
    dplyr::left_join(dplyr::select(parameters, parmNames, nBackgroundMuts), by = c("sampleNames" = "parmNames")) |> 
    # join the information of the generated kataegis foci
    dplyr::left_join(dplyr::select(dataSynthetic$reportedKataegisFoci, sampleNames, kataegis), by = "sampleNames") |> 
    # remove duplicate rows
    dplyr::distinct() |> 
    dplyr::mutate(
        # add column which specifies if a kataegis event was detected by the method
        detectedKataegisInSample = dplyr::if_else(is.na(.data$totalVariants), FALSE, TRUE),
        # add column which specifies tumor mutational burden (TMB)
        TMB = dplyr::case_when(
            nBackgroundMuts == 25 ~ 0.1,
            nBackgroundMuts == 125 ~ 0.5,
            nBackgroundMuts == 249 ~ 1,
            nBackgroundMuts == 1246 ~ 5,
            nBackgroundMuts == 2493 ~ 10,
            nBackgroundMuts == 12463 ~ 50,
            nBackgroundMuts == 24925 ~ 100,
            nBackgroundMuts == 124625 ~ 500
        )
    ) |> 
    # make more clear that the kataegis column only specifies if the sample contains a kataegis event
    dplyr::rename(kataegisInSample = kataegis)
```

Calculate the performance of the kataegis detection tools regarding sample classfication on the synthetic dataset
```{r}
resultsPerSample <- resultsSynthetic |> 
    # summarise if a method detected kataegis in a sample
    group_by(package, sampleNames, runTime) |> 
    summarise(
        .groups = "keep",
        # is a kataegis foci detected by the method
        detectedKataegisInSample = any(detectedKataegisInSample),
        # is there actualy a kataegis foci in that sample
        kataegisInSample = any(kataegisInSample),
        # Tumor mutational burden of sample
        TMB = unique(TMB)
    ) |> 
    ungroup() |> 
    rowwise() |> 
    # calculate confusion matrix
    mutate(
        TP = detectedKataegisInSample == TRUE & kataegisInSample == TRUE,
        FP = detectedKataegisInSample == TRUE & kataegisInSample == FALSE,
        TN = detectedKataegisInSample == FALSE & kataegisInSample == FALSE,
        FN = detectedKataegisInSample == FALSE & kataegisInSample == TRUE
    ) |> 
    ungroup()

# performance of each package over the whole dataset
performancePerSample <- resultsPerSample |> 
    group_by(package) |> 
    dplyr::group_modify(~ calculateMetrics(.x), .keep = TRUE) |> 
    ungroup()

performancePerSampleTMB <- resultsPerSample |> 
    group_by(package, TMB) |> 
    dplyr::group_modify(~ calculateMetrics(.x), .keep = TRUE) |> 
    ungroup()
```

```{r}
resultsPerVariant <- resultsSynthetic |>
    dplyr::group_by(package, sampleNames) |>
    dplyr::group_modify(~ calculateConfusionVariants(.x, variantData = dataSynthetic), .keep = TRUE) |>
    ungroup()

performancePerVariant <- resultsPerVariant |> 
    group_by(package) |> 
    dplyr::group_modify(~ calculateMetrics(.x), .keep = TRUE) |> 
    ungroup()|>  
    arrange(desc(nMCC)) |> 
    dplyr::select(package, accuracy, nMCC, F1, TPR, TNR)

performancePerVariantTMB <- resultsPerVariant |> 
    group_by(package, TMB) |> 
    dplyr::group_modify(~ calculateMetrics(.x), .keep = TRUE) |> 
    ungroup()
```

Plot nMCC as a function of the TMB for each package
```{r}
levelOrderTMB <- c("Low (TMB < 0.1)", "Mid (0.1 >= TMB < 10)", "High (TMB >= 10)")
levelOrderTMB <- c("low", "mid", "high")
levelOrderPackages <- factor(performancePerVariant$package, levels = arrange(performancePerVariant, nMCC)$package)

colors = c('ClusteredMutations' = '#66C2A5', 'kataegis' = '#FC8D62', 'katdetectr' = '#8DA0CB', 'MafTools' = '#E78AC3', 'SeqKat' = '#A6D854', 'SigProfilerClusters' = '#FFD92F')

plotnMMC.Alex <- performancePerVariantTMB |> 
    ggplot2::ggplot(aes(
        x = factor(TMBcat, levels = levelOrderTMB), 
        y = nMCC, 
        group = factor(package, levels = levelOrderPackages), 
        colour = factor(package, levels = levelOrderPackages))) +
    ggplot2::geom_line(size = 0.5, alpha = 0.4, lty = 11) +
    ggplot2::geom_point(aes(x = factor(TMBcat, levels = levelOrderTMB), y = nMCC, fill = package), col = 'black', shape = 21, lwd = 2, position = ggbeeswarm::position_quasirandom(width = .05)) +
    ggplot2::scale_fill_manual(values = colors, guide = 'none') +
    ggplot2::scale_color_manual(values = colors, guide = 'none') +
    ggplot2::scale_x_discrete(labels=c(
        "low" = "Low (TMB < 0.1)<br>n = 301", 
        "mid" = "Mid (0.1 ≥ TMB < 10)<br>n = 186",
        "high" = "High (TMB ≥ 10)<br>n = 20")
    ) +
    ggplot2::ylim(0.5, 1) +
    ggplot2::xlab("TMB class") +
    theme_Job
```


Plot nMCC as a function of the TMB for each packge
```{r}
# use package ordering from total nMCC score on the Alexandrov dataset
levelOrderPackages <- c("katdetectr", "SeqKat", "MafTools", "SigProfilerClusters", "ClusteredMutations", "kataegis")

plotLinenMCCperTMB <- performancePerVariantTMB |> 
    ggplot2::ggplot(aes(
        x = factor(TMB), 
        y = nMCC, 
        group = package, 
        colour = factor(package, levels = levelOrderPackages))) +
    geom_line(size = 0.8, alpha = 0.3) +
    geom_point(aes(x = factor(TMB), y = nMCC)) +
    theme_light() +   
    scale_colour_discrete("Package") +
    ylim(0.5, 1) +
    xlab("TMB class") +
    scale_x_discrete(labels=c("0.1" = "0.1\n n = 128",
                              "0.5" = "0.5\n n = 128", 
                              "1" = "1\n n = 128",
                              "5" = "5\n n = 128",
                              "10" = "10\n n = 128",
                              "50" = "50\n n = 128",
                              "100" = "100\n n = 128",
                              "500" = "500\n n = 128")) +
    ggtitle("Performance on synthetic data") 
    #theme(legend.position="none")

ggsave(file = "../../katdetectr_manusscript/figures/plotSyntheticLinenMCCperTMB.jpeg", plotLinenMCCperTMB, width = 7, height = 3)

plotnMMC.Syn <- performancePerVariantTMB |> 
    ggplot2::ggplot(aes(x = factor(TMB), y = nMCC, group = package, colour = factor(package, levels = levelOrderPackages))) +
    ggplot2::geom_line(size = 0.5, alpha = 0.4, lty = 11) +
    ggplot2::geom_point(aes(y = nMCC, fill = package), col = 'black', shape = 21, lwd = 2, position = ggbeeswarm::position_quasirandom(width = .05)) +
    ggplot2::scale_fill_manual(values = colors, guide = 'none') +
    ggplot2::scale_color_manual(values = colors, guide = 'none') +
    ggplot2::scale_x_discrete(labels=c(
        "low" = "Low (TMB < 0.1)<br>n = 301", 
        "mid" = "Mid (0.1 ≥ TMB < 10)<br>n = 186",
        "high" = "High (TMB ≥ 10)<br>n = 20")
    ) +
    ggplot2::ylim(0.5, 1) +
    ggplot2::labs(x = "TMB class", y  = 'nMCC<br>Synthetic dataset') +
    theme_Job +
    scale_x_discrete(labels=c(
        "0.1" = "0.1<br>n = 128",
        "0.5" = "0.5<br>n = 128", 
        "1" = "1<br>n = 128",
        "5" = "5<br>n = 128",
        "10" = "10<br>n = 128",
        "50" = "50<br>n = 128",
        "100" = "100<br>n = 128",
        "500" = "500<br>n = 128")
    )
```


```{r}
# facet labels
TMB.labs <- c("TMB: 500", "TMB: 100", "TMB: 50", "TMB: 10", "TMB: 5", "TMB: 1", "TMB: 0.5", "TMB: 0.1")
names(TMB.labs) <- c(500, 100, 50, 10, 5, 1, 0.5, 0.1)

plotPerformancePerVariantTMB <- performancePerVariantTMB |> 
    tidyr::pivot_longer(
        cols = c(accuracy, TPR, TNR, F1, nMCC),
        names_to = "performanceMetric",
        values_to = "value"
    ) |> 
    mutate(TMB = factor(TMB, levels = c(500, 100, 50, 10, 5, 1, 0.5, 0.1))) |> 
    ggplot2::ggplot(aes(y = factor(package, levels = arrange(performancePerVariant, nMCC)$package), 
                        x = factor(performanceMetric, levels = c("accuracy", "nMCC", "F1", "TPR", "TNR")), 
                        label = round(value, 4), 
                        fill = value)) +
    ggplot2::geom_tile(color = 'grey25') +
    scale_fill_gradientn(colors = hcl.colors(20, "RdYlGn"), values = c(0,0.5,1)) +
    ggplot2::ylab("Package") +
    ggplot2::xlab("Performance on synthetic data split on TMB") +
    scale_x_discrete(position = "top") +
    theme(
        axis.text.x = element_text(angle = 0, ),
        text = ggplot2::element_text(size=5, family='Helvetica'),
        strip.background = ggplot2::element_blank(),
        panel.background = element_blank(),
        legend.title = element_blank()
    ) +
    ggplot2::geom_text(size = 1.5, angle = 0) +
    facet_grid(TMB ~ ., labeller = labeller(TMB = rev(TMB.labs)))
```

```{r}
plotRunTimes.Syn <- resultsPerSample |> 
     ggplot2::ggplot(mapping = aes(x = factor(package, levels = arrange(performancePerSample, meanRuntime)$package), y = runTime/60, fill = package)) + 
     gghalves::geom_half_point_panel(size = 1, col = 'black', shape = 21) +
     gghalves::geom_half_boxplot(outlier.shape = NA) +
     ggplot2::scale_fill_manual(values = colors, guide = 'none') +
     ggplot2::scale_color_manual(values = colors, guide = 'none') +
     ggplot2::scale_y_continuous(trans = scales::pseudo_log_trans(), breaks = c(seq(0,1,by =.2), 0:20)) +
     ggplot2::labs(y = "Runtime in minutes<br>(Synthetic dataset; log <sub>10</sub>)", x = 'Packages') +
     ggplot2::geom_text(data = resultsPerSample %>% dplyr::group_by(package) %>% dplyr::summarise(mean = mean(runTime, na.rm = T)), aes(x = package, y = -.1, label = round(mean, 1)), size = 3, fontface='bold') +
     theme_Job
```


```{r}
# facet labels
detectedKataegisInSample.labs <- c("Kataegis Samples", "Non Kataegis Samples")
names(detectedKataegisInSample.labs) <- c(TRUE, FALSE)

# Total runtimes of all PCF methods 
plotRunTimesTotal <- resultsPerSample |> 
    ggplot(mapping = aes(x = factor(package, levels = arrange(performancePerSample, meanRuntime)$package), y = runTime/60)) + 
    geom_boxplot(outlier.size = 0.5) +
    ggplot2::ylab("Run times (minutes)") +
    ggplot2::xlab("Package name") +
    ggtitle("Total runtimes of kataegis detection tools Synthetic dataset")  +
    theme_light() +
    theme(axis.text.x = element_text( size = 10))

ggsave(file = "../../katdetectr_manusscript/figures/plotSyntheticRuntimesTotal.jpeg", plotRunTimesTotal, width = 12, height = 4)


plotRunTimesTotallog10 <- resultsPerSample |> 
    ggplot(mapping = aes(x = factor(package, levels = arrange(performancePerSample, meanRuntime)$package), y = runTime/60)) + 
    geom_boxplot(outlier.size = 0.5) +
    ggplot2::ylab("Run times (minutes)") +
    ggplot2::xlab("Package name") +
    ggtitle("Total runtimes of kataegis detection tools Synthetic dataset log10 scale")  +
    theme_light() +
    theme(axis.text.x = element_text( size = 10)) + 
    coord_trans(y = "log10")

ggsave(file = "../../katdetectr_manusscript/figures/plotSyntheticRuntimesTotallog10.jpeg", plotRunTimesTotallog10, width = 12, height = 4)
```
